//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saber.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SaberRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SaberRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saber.Settings.SaberRes", typeof(SaberRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string DatamemberBracketClose {
            get {
                return ResourceManager.GetString("DatamemberBracketClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string DatamemberBracketOpen {
            get {
                return ResourceManager.GetString("DatamemberBracketOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  = .
        /// </summary>
        internal static string DatamemberEquals {
            get {
                return ResourceManager.GetString("DatamemberEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the passed Guids are empty.
        /// </summary>
        internal static string EmptyGuids {
            get {
                return ResourceManager.GetString("EmptyGuids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string EndOfSentence {
            get {
                return ResourceManager.GetString("EndOfSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string ErrorSeparator {
            get {
                return ResourceManager.GetString("ErrorSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception of type {0} should have been thrown.
        /// </summary>
        internal static string ExceptionNotThrown {
            get {
                return ResourceManager.GetString("ExceptionNotThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Args: .
        /// </summary>
        internal static string GuardErrorMessage {
            get {
                return ResourceManager.GetString("GuardErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class: {0} - Method: {1} - .
        /// </summary>
        internal static string GuardErrorMessageBase {
            get {
                return ResourceManager.GetString("GuardErrorMessageBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all arguments can not be converted to Guids.
        /// </summary>
        internal static string GuidParseError {
            get {
                return ResourceManager.GetString("GuidParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid email has been passed..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all booleans are false.
        /// </summary>
        internal static string IsFalse {
            get {
                return ResourceManager.GetString("IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type was passed that wasn&apos;t serializable.
        /// </summary>
        internal static string IsSerializable {
            get {
                return ResourceManager.GetString("IsSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all booleans are true.
        /// </summary>
        internal static string IsTrue {
            get {
                return ResourceManager.GetString("IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative numbers have been passed..
        /// </summary>
        internal static string NegativeNumbers {
            get {
                return ResourceManager.GetString("NegativeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative numbers or zero have been passed..
        /// </summary>
        internal static string NegativeNumbersOrZero {
            get {
                return ResourceManager.GetString("NegativeNumbersOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments.
        /// </summary>
        internal static string NoArguments {
            get {
                return ResourceManager.GetString("NoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all passed dates are in the future.
        /// </summary>
        internal static string NotAllDatesAreInTheFuture {
            get {
                return ResourceManager.GetString("NotAllDatesAreInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all passed dates are in the past.
        /// </summary>
        internal static string NotAllDatesAreInThePast {
            get {
                return ResourceManager.GetString("NotAllDatesAreInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the passed arguments aren&apos;t compliant with the given expression.
        /// </summary>
        internal static string NotCompliant {
            get {
                return ResourceManager.GetString("NotCompliant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL, empty or whitespace has been passed.
        /// </summary>
        internal static string NullEmptyOrWhiteSpaceHasBeenPassed {
            get {
                return ResourceManager.GetString("NullEmptyOrWhiteSpaceHasBeenPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL has been passed.
        /// </summary>
        internal static string NullHasBeenPassed {
            get {
                return ResourceManager.GetString("NullHasBeenPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive numbers have been passed..
        /// </summary>
        internal static string PositiveNumbers {
            get {
                return ResourceManager.GetString("PositiveNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive numbers or zero have been passed..
        /// </summary>
        internal static string PostiveNumbersOrZero {
            get {
                return ResourceManager.GetString("PostiveNumbersOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string SentenceSeparator {
            get {
                return ResourceManager.GetString("SentenceSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start datetime is after or equal to end datetime.
        /// </summary>
        internal static string StartBeforeEndDate {
            get {
                return ResourceManager.GetString("StartBeforeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} can not be assigned to {1}.
        /// </summary>
        internal static string TypeCannotBeAssigned {
            get {
                return ResourceManager.GetString("TypeCannotBeAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} can not be assigned to {1}: interface is not implemented.
        /// </summary>
        internal static string TypeCannotBeAssignedInterface {
            get {
                return ResourceManager.GetString("TypeCannotBeAssignedInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of the wrong type was thrown.\n\nExpected: &lt;{0}&gt;\nActual: &lt;{1}&gt;.
        /// </summary>
        internal static string WrongException {
            get {
                return ResourceManager.GetString("WrongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception messages are not equal.\n\nExpected: &lt;{0}&gt;\nActual: &lt;{1}&gt;.
        /// </summary>
        internal static string WrongMessage {
            get {
                return ResourceManager.GetString("WrongMessage", resourceCulture);
            }
        }
    }
}
